baseURL = "https://jan07.com/"
title = "Jan07"

[permalinks]
    post = "/blog/:slug"

[menu]

  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 10

  [[menu.main]]
    name = "Videos"
    url = "/videos"
    weight = 20

  [[menu.main]]
    name = "Skills"
    url = "/skills"
    weight = 30

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 40

  [[menu.social]]
    name = "GitHub"
    pre = "github"
    url = "https://github.com/jan07-official"
    weight = 10

  [[menu.social]]
    name = "YouTube"
    pre = "youtube"
    url = "https://youtube.com/@jan07-official"
    weight = 20

  [[menu.social]]
    name = "RSS Feed"
    pre = "rss"
    url = "/index.xml"
    weight = 30



[markup]
  [markup.goldmark.parser]
    wrapStandAloneImageWithinParagraph = false
  [markup.highlight]
    style = 'catppuccin-macchiato'
